variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    -s .m2/settings.xml

  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"

default:
  image: maven:3.8.6-eclipse-temurin-17-alpine
  tags:
    - shared


cache:
  paths:
    - .m2/repository/
    - target/
    - .sonar/cache

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - quality
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

lint:
  stage: test
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=spectrum-GC -Dsonar.java.binaries=target

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - main